letter =
    "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J"
  | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T"
  | "U" | "V" | "W" | "X" | "Y" | "Z"
  | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j"
  | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t"
  | "u" | "v" | "w" | "x" | "y" | "z"
  ;

digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

sign = "+" | "-" ;
underscore = "_" ;

(* ========== IDENTIFIER ========== *)
identifier = letter, { [ underscore ], ( letter | digit ) } ;

(* ========== INTEGER ========== *)

digit_sequence    = digit, { digit } ;
unsigned_integer  = digit_sequence ;
signed_integer    = [ sign ], unsigned_integer ;

extended_digit    = digit | letter ;
extended_number   = unsigned_integer, "#", extended_digit, { extended_digit } ;

integer_literal   = signed_integer | extended_number ;

(* ========== REAL ========== *)

exponent_part = ("e" | "E"), [ sign ], digit_sequence ;

(* «полные» вещественные: 123.456, 123e10, 123.456e-7 *)
unsigned_real = digit_sequence, ".", digit_sequence, [ exponent_part ]
              | digit_sequence, exponent_part ;

(* «укороченные» вещественные: 123., .5, .5e3, 123.e5 *)
short_unsigned_real = digit_sequence, ".", [ exponent_part ]
                    | ".", digit_sequence, [ exponent_part ] ;

signed_real = [ sign ], ( unsigned_real | short_unsigned_real ) ;
real_literal = signed_real ;

(* ========== STRING ========== *)

apostrophe = "'" ;
apostrophe_pair = "''" ;

printable_not_apostrophe =
    " " | "!" | '"' | "#" | "$" | "%" | "&"
  | "(" | ")" | "*" | "+" | "," | "-" | "." | "/"
  | digit
  | ":" | ";" | "<" | "=" | ">" | "?" | "@"
  | letter
  | "[" | "\" | "]" | "^" | "_" | "`" | "{" | "|" | "}" | "~"
  ;

string_element = apostrophe_pair | printable_not_apostrophe ;
character_string = apostrophe, { string_element }, apostrophe ;
string_literal = character_string ;

(* ========== UNION + ROOT ========== *)

number_literal = integer_literal | real_literal ;
lexeme = identifier | number_literal | string_literal ;