<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4.Runtime.Standard" Version="4.13.1" />
    <PackageReference Include="Antlr4BuildTasks" Version="12.11.0" />
  </ItemGroup>

  <ItemGroup>
    <Antlr4 Include="Grammars\DeaExprLexer.g4">
      <Package>Grammar.Generated</Package>
      <Listener>false</Listener>
      <Visitor>false</Visitor>
    </Antlr4>

    <Antlr4 Include="Grammars\DeaExprParser.g4">
      <Package>Grammar.Generated</Package>
      <Listener>false</Listener>
      <Visitor>false</Visitor>
    </Antlr4>
  </ItemGroup>


</Project>
